name: learn-github-actions
on: push
jobs:
  display-msg:
    runs-on: ubuntu-latest
    steps:
      - name:  Checkout code
        uses: actions/checkout@v4
      - name:  Echo Hello world
        run:  echo "Hello, World!"
