name: Push or Pull Request Workflow

on: [push, pull_request]

env:
  PUSH_MSG: "C'est un push !"
  PULL_MSG: "C'est une pull request !"

jobs:
  check-event:
    runs-on: ubuntu-latest
    steps:
      - name: Conditional step for pull requests
        if: ${{ github.event_name == 'pull_request' }}
        run: echo "${PULL_MSG}"

      - name: Conditional step for pushes
        if: ${{ github.event_name == 'push' }}
        run: echo "${PUSH_MSG}"




