name: learn-github-actions
on: push
jobs:
  display-msg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          node-version: '20'
      - run:  echo "Hello, World!"
