name: Pull Request Workflow

on: [push, pull_request]

jobs:
  check-event:
    runs-on: ubuntu-latest
    steps:
      - name: Conditional step for pull requests
        if: ${{ github.event_name == 'pull_request' }}
        run: echo "This step runs only for pull requests."

      - name: Conditional step for pushes
        if: ${{ github.event_name == 'push' }}
        run: echo "This step runs only for pushes."